{{- $name := include "name" . -}}
{{- $fullName := include "fullname" . -}}
{{- $chart := include "chart" . -}}

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingressClass | default "nginx" }}
spec:
  rules:
    - host: "{{$fullName}}.{{.Values.global.backendIngressDomain}}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http