

apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotnet1.fullname" . }}
  labels:
    {{- include "dotnet1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    {{- include "dotnet1.selectorLabels" . | nindent 4 }}
